# Generated by Django 4.0.4 on 2022-04-28 15:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('departure_airport', models.CharField(max_length=255)),
                ('arrival_airport', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('stops', models.IntegerField()),
                ('airline_name', models.CharField(max_length=255)),
                ('airline_id', models.CharField(max_length=255)),
                ('duration_mins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='invalid price', regex='^\\d+(\\.\\d{1,2})?$')])),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.agent')),
                ('legs', models.ManyToManyField(to='api.leg')),
            ],
        ),
    ]
